### ISSUE TITLE
The docs that are linked in the README.md are not working

### ISSUE THREAD

**Issue by th0bse** [kordlib/kord#262]
If you click on the link for the Dokka docs, and then try to view the docs for a specific module, you always get a 404.

I already pointed this out in the discord but for the sake of being able to track this issue, I'm mentioning it here too.

**Comment by DRSchlaubi** [comment]
https://kordlib.github.io/kord/ Works for me

**Comment by th0bse** [comment]
But not for the actual modules. The overview works for me too, but nothing beyond that.

**Comment by DRSchlaubi** [comment]
Yep just notice that

**Comment by DRSchlaubi** [comment]
https://github.com/kordlib/kord/blob/6f0863d284b2e66617a2eb9b0fa5d48a2a512ab5/.github/workflows/docs-ci.yml#L4-L8

The problem is docs are only build for master.

You can see docs here: 
Rest: https://repo1.maven.org/maven2/dev/kord/kord-rest/0.7.0-RC2/kord-rest-0.7.0-RC2-sources.jar
Gateway: https://repo1.maven.org/maven2/dev/kord/kord-gateway/0.7.0-RC2/kord-gateway-0.7.0-RC2-sources.jar
Core: https://repo1.maven.org/maven2/dev/kord/kord-core/0.7.0-RC2/kord-core-0.7.0-RC2-sources.jar
Core: https://repo1.maven.org/maven2/dev/kord/kord-common/0.7.0-RC2/kord-common-0.7.0-RC2-sources.jar

**Comment by HopeBaron** [comment]
The problem is with Dokka itself and using javadocs/kotlin docs doesn't help fixing the actual problem I guess that's why @th

**Comment by DRSchlaubi** [comment]
What do you mean with the actual Problem?

**Comment by HopeBaron** [comment]
the fact that the docs give 404 for modules

**Comment by DRSchlaubi** [comment]
Yes I just linked the docs as a temporary workaround

**Comment by th0bse** [comment]
I am just using the javadocs/kotlindocs locally right now and I'm fine with it, so this isn't a priority or anything for me by any means, it's still an "unpleasant hurdle" for people who are thinking about using kord for their projects. 

That was the whole intention behind opening this issue.

**Comment by th0bse** [comment]
It's working again, tested on 2 different machines in different networks.
