### ISSUE TITLE
getPresence error

### ISSUE THREAD

**Issue by hands8142** [kordlib/kord#307]
```
Presence for Member with id 778570545935024149 in guild 695541052593012788 was not found.
```

This error occurs. I'm in the guild, but it says I can't find it.

**Comment by HopeBaron** [comment]
Hello there, presences are cached from the gateway, if there is no presence you would get this error since you are calling getPresence instead of getPresenceOrNull.

However, you can request the presences from the gateway (taking into consideration you enable correct intents)
You can call `guild.requestMembers()` which in turn cache presences.

or enable GUILD_PRESENCE intent which will return members in guild creation events and caching presences in turn.

**Comment by hands8142** [comment]
GUILD_PRESENCE is already enabled

**Comment by HopeBaron** [comment]
Make sure it's enabled under your Application > Bot tab since it's a privileged intent.
And if it is, you must make sure that you have enabled it in the bot's configuration as well 

```kt
 Kord("TOKEN") {
        intents = Intents(Intent.GuildPresences)
    }
```

**Comment by hands8142** [comment]
Some can be recalled, some can't be retrieved.

**Comment by HopeBaron** [comment]
could you elaborate?

**Comment by hands8142** [comment]
A few people work. But other people don't work. It doesn't seem to work for offline people. If you use getPresenceOrNull, you can receive null without error.

**Comment by HopeBaron** [comment]
To my knowledge, Discord doesn't return status' if a user is offline. so you receive null.

**Comment by hands8142** [comment]
Thank you.
