### ISSUE TITLE
Proposal, Add slash command builder

### ISSUE THREAD

**Issue by NoakPalander** [kordlib/kord#359]
Currently adding slash commands work something like
```kt
client.guilds.collect {
        it.createApplicationCommand("name", "description") {
            // fields..
        }
}
``` 
only to later add a specific event handler like
```kt
client.on<InteractionCreateEvent> {
    // check what slash command it was and then run some function..
}
``` 
IMO it would be nicer if we had something like a slash command creator akin to Kord's many other creators / builders, perhaps something in the fashion of
```kt
client.slashes {
    slash("name", "description") { // member of a "SlashCreateBuilder"
        // when the command is added
        onCreate { // ApplicationCommandCreateBuilder or GlobalCommand..
            // fields
        }
        onEvent { // member of InteractionCreateEvent
            
        }
    }
}
```
and thus you have a clean way to both create and respond to slash commands

**Comment by HopeBaron** [comment]
First I would like to suggest a better way to register common commands using the `kord.createGlobalApplicationCommand` builder which would register the given command for all guilds instead of iterating through the whole flow of guilds available.

Next, I would like to clarify that slash commands are not limited to gateway. In other words, bots can also handle application command through webhooks.

**Comment by HopeBaron** [comment]
it depends on how you are going to establish a connection thus how you are going to respond to it.
If you would like not to worry about how to register commands and it feels like a pain to deal with nor that you would like to create your own abstractions.
You might want to look at this [list of comparisons](https://kordex.kotlindiscord.com/en/framework-comparison) for command framework made on top of Kord:
