### ISSUE TITLE
Detecting voice channel disconnects

### ISSUE THREAD

**Issue by H4kt** [kordlib/kord#710]
Hey there
I'm looking for a way to detect voice channel disconnects.
I've already looked into [voice documentation](https://github.com/kordlib/kord/blob/0.8.x/voice/README.md), however I didn't find a way to detect it.

**Comment by dookon** [comment]
Hello! You can know if someone has been disconnected by the `VoiceStateUpdateEvent`, take a look:
```kt
kord.on<VoiceStateUpdateEvent> {
        if ((old?.channelId != null && state.channelId == null) || (old?.channelId != null && state.channelId != null))
            println("disconnected")
    }
```
* `old?.channelId != null && state.channelId == null`
Old represents the user before the action and state, after the action. If old.channelId is different from null, it means that he left the channel, and since he left, the state.channelId should be null!

* `old?.channelId != null && state.channelId != null`
We need to be careful because it may have gone from one channel to the other "switch", so the old will not be null and neither will the state!

**Comment by H4kt** [comment]
> Hello! You can know if someone has been disconnected by the `VoiceStateUpdateEvent`, take a look:
> 
> ```kotlin
> kord.on<VoiceStateUpdateEvent> {
>         if ((old?.channelId != null && state.channelId == null) || (old?.channelId != null && state.channelId != null))
>             println("disconnected")
>     }
> ```
> 
> * `old?.channelId != null && state.channelId == null`
>   Old represents the user before the action and state, after the action. If old.channelId is different from null, it means that he left the channel, and since he left, the state.channelId should be null!
> * `old?.channelId != null && state.channelId != null`
>   We need to be careful because it may have gone from one channel to the other "switch", so the old will not be null and neither will the state!

That works, thank you
You should really add this into documentation
